- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Get facts for a specific image
    azure_rm_virtualmachineimage_info:
      location: eastasia
      publisher: MicrosoftWindowsServer
      test: we are testing only. 
      offer: WindowsServer
      version: latest
